### ISSUE TITLE
You didn't give your wowuphub listing a name.

### ISSUE THREAD

**Issue by cdmichaelb** [kwilliams1987/DynamicUI#1]
It shows up as a blank addon. 

![image](https://github.com/kwilliams1987/DynamicUI/assets/1451709/18de0ecb-136b-4f83-b0f1-be2596dcd61e)

**Comment by kwilliams1987** [comment]
I didn't submit the AddOn to WowUpHub yet, only CurseForge.

Is this in the WowUp application or somewhere else?

**Comment by cdmichaelb** [comment]
https://wowup.io/addons/2797834

It's also in the wowup application.  I didn't realize they're putting stuff on their page automatically now.

**Comment by kwilliams1987** [comment]
This has been fixed in v1.0.3.

Curse won't let me upload a new version right now but should be submitted soon.

**Comment by kwilliams1987** [comment]
This has been fixed in v1.0.3.
